spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: diplom_offer
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
      bindings:
        offer-out:
          destination: offer-out
          binder: kafka
        offer-in:
          destination: offer-in
          binder: kafka
server:
  port: 8085