spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: diplom_offer
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST}
      bindings:
        offer-out:
          destination: ${KAFKA_OFFER_OUT_DEST}
          binder: kafka
        offer-in:
          destination: ${KAFKA_OFFER_IN_DEST}
          binder: kafka
server:
  port: ${TOMCAT_PORT}